export { HomePage } from './HomePage'
export { LoginPage } from './LoginPage'
export { RegisterPage } from './RegisterPage'
export { EstudianteDashboard } from './EstudianteDashboard'
export { AdminDashboard } from './AdminDashboard'
